<?php
//Sumales 1 por naco estupido
//Perfil de escalas basicas MMPI-2

class basicScalesMale{

   private $c;

   //sumatoria de respuesta verdadero
   function calif_True($answer){
      if($answer == 'true'){
         $this->c++;
      }
   }
   
   //Sumatoria de respuesta falso
   function calif_False($answer){
     if($answer == 'false'){
         $this->c++;
     }
   }

   function scale_L($answer = array()){
      $this-> c = 0;
      $this->calif_False($answer[16]);
      $this->calif_False($answer[29]);
      $this->calif_False($answer[41]);
      $this->calif_False($answer[51]);
      $this->calif_False($answer[77]);
      $this->calif_False($answer[93]);
      $this->calif_False($answer[102]);
      $this->calif_False($answer[107]);
      $this->calif_False($answer[123]);
      $this->calif_False($answer[138]);
      $this->calif_False($answer[153]);
      $this->calif_False($answer[183]);
      $this->calif_False($answer[203]);
      $this->calif_False($answer[232]);
      $this->calif_False($answer[260]);
      return $this->c;
   }

   //t = true, f = false
   function scale_F($answer){
      $this-> c = 0;
      $this->calif_False($answer[6]);
      $this->calif_False($answer[12]);
      $this->calif_True($answer[18]);
      $this->calif_True($answer[24]);
      $this->calif_True($answer[30]);
      $this->calif_True($answer[36]);
      $this->calif_True($answer[54]);
      $this->calif_True($answer[60]);
      $this->calif_True($answer[66]);
      $this->calif_True($answer[72]);
      $this->calif_False($answer[78]);
      $this->calif_True($answer[84]);
      $this->calif_False($answer[90]);
      $this->calif_True($answer[96]);
      $this->calif_False($answer[102]);
      $this->calif_False($answer[108]);
      $this->calif_True($answer[114]);
      $this->calif_False($answer[120]);
      $this->calif_False($answer[126]);
      $this->calif_False($answer[132]);
      $this->calif_True($answer[138]);
      $this->calif_True($answer[144]);
      $this->calif_True($answer[150]);
      $this->calif_True($answer[156]);
      $this->calif_True($answer[162]);
      $this->calif_True($answer[168]);
      $this->calif_False($answer[174]);
      $this->calif_True($answer[180]);
      $this->calif_False($answer[186]);
      $this->calif_False($answer[190]);
      $this->calif_True($answer[198]);
      $this->calif_False($answer[204]);
      $this->calif_False($answer[210]);
      $this->calif_True($answer[216]);
      $this->calif_False($answer[222]);
      $this->calif_True($answer[228]);
      $this->calif_True($answer[234]);
      $this->calif_True($answer[240]);
      $this->calif_True($answer[246]);
      $this->calif_True($answer[252]);
      $this->calif_True($answer[258]);
      $this->calif_True($answer[264]);
      $this->calif_True($answer[270]);
      $this->calif_False($answer[276]);
      $this->calif_True($answer[282]);
      $this->calif_True($answer[288]);
      $this->calif_True($answer[294]);
      $this->calif_True($answer[300]);
      $this->calif_True($answer[306]);
      $this->calif_True($answer[312]);
      $this->calif_False($answer[318]);
      $this->calif_True($answer[324]);
      $this->calif_False($answer[330]);
      $this->calif_True($answer[336]);
      $this->calif_False($answer[343]);
      $this->calif_True($answer[349]);
      $this->calif_True($answer[355]);
      $this->calif_True($answer[361]);
      return $this->c;
   }
   
   function scale_K(){
      $this-> c = 0;
      $this->calif_False($answer[29]);
      $this->calif_False($answer[37]);
      $this->calif_False($answer[58]);
      $this->calif_False($answer[76]);
      $this->calif_True($answer[83]);
      $this->calif_False($answer[110]);
      $this->calif_False($answer[116]);
      $this->calif_False($answer[122]);
      $this->calif_False($answer[127]);
      $this->calif_False($answer[130]);
      $this->calif_False($answer[136]);
      $this->calif_False($answer[148]);
      $this->calif_False($answer[157]);
      $this->calif_False($answer[158]);
      $this->calif_False($answer[167]);
      $this->calif_False($answer[171]);
      $this->calif_False($answer[196]);
      $this->calif_False($answer[213]);
      $this->calif_False($answer[243]);
      $this->calif_False($answer[267]);
      $this->calif_False($answer[284]);
      $this->calif_False($answer[290]);
      $this->calif_False($answer[330]);
      $this->calif_False($answer[338]);
      $this->calif_False($answer[339]);
      $this->calif_False($answer[341]);
      $this->calif_False($answer[346]);
      $this->calif_False($answer[348]);
      $this->calif_False($answer[356]);
      $this->calif_False($answer[365]);
      return $this->c;
   }
   //
   function scale_Hs(){
      $this-> c = 0;
      $this->calif_False($answer[2]);
      $this->calif_False($answer[3]);
      $this->calif_False($answer[8]);
      $this->calif_False($answer[10]);
      $this->calif_False($answer[18]);
      $this->calif_False($answer[20]);
      $this->calif_True($answer[28]);
      $this->calif_True($answer[39]);
      $this->calif_False($answer[45]);
      $this->calif_False($answer[47]);
      $this->calif_True($answer[53]);
      $this->calif_False($answer[57]);
      $this->calif_True($answer[59]);
      $this->calif_False($answer[91]);
      $this->calif_True($answer[97]);
      $this->calif_True($answer[101]);
      $this->calif_True($answer[111]);
      $this->calif_False($answer[117]);
      $this->calif_False($answer[141]);
      $this->calif_False($answer[143]);
      $this->calif_True($answer[149]);
      $this->calif_False($answer[152]);
      $this->calif_False($answer[164]);
      $this->calif_False($answer[173]);
      $this->calif_True($answer[145]);
      $this->calif_False($answer[176]);
      $this->calif_False($answer[179]);
      $this->calif_False($answer[208]);
      $this->calif_False($answer[224]);
      $this->calif_True($answer[247]);
      $this->calif_False($answer[249]);
      $this->calif_False($answer[255]);
      return $this->c;
   }
   //
   function scale_D(){
      $this-> c = 0;
      $this->calif_False($answer[2]);
      $this->calif_True($answer[5]);
      $this->calif_False($answer[9]);
      $this->calif_False($answer[10]);
      $this->calif_True($answer[15]);
      $this->calif_True($answer[18]);
      $this->calif_False($answer[20]);
      $this->calif_False($answer[29]);
      $this->calif_True($answer[31]);
      $this->calif_False($answer[33]);
      $this->calif_False($answer[37]);
      $this->calif_True($answer[38]);
      $this->calif_True($answer[39]);
      $this->calif_False($answer[43]);
      $this->calif_False($answer[45]);
      $this->calif_True($answer[46]);
      $this->calif_False($answer[49]);
      $this->calif_False($answer[55]);
      $this->calif_True($answer[56]);
      $this->calif_False($answer[68]);
      $this->calif_True($answer[73]);
      $this->calif_False($answer[75]);
      $this->calif_False($answer[76]);
      $this->calif_True($answer[92]);
      $this->calif_False($answer[95]);
      $this->calif_False($answer[109]);
      $this->calif_True($answer[117]);
      $this->calif_False($answer[118]);
      $this->calif_True($answer[127]);
      $this->calif_True($answer[130]);
      $this->calif_False($answer[134]);
      $this->calif_False($answer[140]);
      $this->calif_False($answer[141]);
      $this->calif_False($answer[142]);
      $this->calif_False($answer[143]);
      $this->calif_True($answer[146]);
      $this->calif_True($answer[147]);
      $this->calif_False($answer[148]);
      $this->calif_False($answer[165]);
      $this->calif_True($answer[170]);
      $this->calif_True($answer[175]);
      $this->calif_False($answer[178]);
      $this->calif_True($answer[181]);
      $this->calif_False($answer[188]);
      $this->calif_False($answer[189]);
      $this->calif_False($answer[198]);
      $this->calif_False($answer[209]);
      $this->calif_False($answer[212]);
      $this->calif_False($answer[224]);
      $this->calif_False($answer[231]);
      $this->calif_False($answer[234]);
      $this->calif_False($answer[246]);
      $this->calif_False($answer[253]);
      $this->calif_False($answer[316]);
      return $this->c;
   }
   //
   function scale_Hi(){
      $this-> c = 0;
      $this->calif_False($answer[2]f
      $this->calif_False($answer[3]f
      $this->calif_False($answer[7]f
      $this->calif_False($answer[8]f
      $this->calif_False($answer[9]f
      $this->calif_False($answer[10]f
      $answer[11]t
      $this->calif_False($answer[14]f
      $answer[18]t
      $this->calif_False($answer[26]f
      $this->calif_False($answer[29]f
      $answer[31]t
      $answer[39]t
      $answer[40]t
      $answer[44]t
      $this->calif_False($answer[45]f
      $this->calif_False($answer[47]f
      $this->calif_False($answer[58]f
      $answer[65]t
      $this->calif_False($answer[76]f
      $this->calif_False($answer[81]f
      $this->calif_False($answer[91]f
      $this->calif_False($answer[95]f
      $this->calif_False($answer[98]f
      $answer[101]t
      $this->calif_False($answer[110]f
      $this->calif_False($answer[115]f
      $this->calif_False($answer[116]f
      $this->calif_False($answer[124]f
      $this->calif_False($answer[125]f
      $this->calif_False($answer[129]f
      $this->calif_False($answer[135]f
      $this->calif_False($answer[141]f
      $this->calif_False($answer[148]f
      $this->calif_False($answer[151]f
      $this->calif_False($answer[152]f
      $this->calif_False($answer[157]f
      $this->calif_False($answer[159]f
      $this->calif_False($answer[161]f
      $this->calif_False($answer[164]f
      $answer[166]t
      $this->calif_False($answer[167]f
      $answer[172]t
      $this->calif_False($answer[173]f
      $answer[175]t
      $this->calif_False($answer[176]f
      $this->calif_False($answer[179]f
      $this->calif_False($answer[185]f
      $this->calif_False($answer[193]f
      $this->calif_False($answer[208]f
      $this->calif_False($answer[213]f
      $this->calif_False($answer[224]f
      $answer[230]t
      $this->calif_False($answer[241]f
      $this->calif_False($answer[243]f
      $this->calif_False($answer[249]f
      $this->calif_False($answer[253]f
      $this->calif_False($answer[263]f
      $this->calif_False($answer[265]f
      return $this->c;
   }
   
   function scale_Dp(){
      $this-> c = 0;
      $answer[9]f
      $answer[12]f
      $answer[17]t
      $answer[21]t
      $answer[22]t
      $answer[31]t
      $answer[32]t
      $answer[34]f
      $answer[35]t
      $answer[42]t
      $answer[52]t
      $answer[54]t
      $answer[56]t
      $answer[70]f
      $answer[71]t
      $answer[79]f
      $answer[82]t
      $answer[83]f
      $answer[89]t
      $answer[94]t
      $answer[95]f
      $answer[99]t
      $answer[105]t
      $answer[113]t
      $answer[122]f
      $answer[125]f
      $answer[129]f
      $answer[143]f
      $answer[157]f
      $answer[158]f
      $answer[160]f
      $answer[167]f
      $answer[171]f
      $answer[185]f
      $answer[195]f
      $answer[202]t
      $answer[209]f
      $answer[214]f
      $answer[217]f
      $answer[219]t
      $answer[225]t
      $answer[226]f
      $answer[243]f
      $answer[259]t
      $answer[261]f
      $answer[263]f
      $answer[264]t
      $answer[266]f
      $answer[267]f
      $answer[288]t
      return $this->c;
   }
   //Sumar uno hacia abajo jsjsjs
   function scale_Mf(){
      $this-> c = 0;
      $answer[0]f
      $answer[3]t
      $answer[18]f
      $answer[24]t
      $answer[25]f
      $answer[26]f
      $answer[61]t
      $answer[62]f
      $answer[63]t
      $answer[66]t
      $answer[67]f
      $answer[68]f
      $answer[73]t
      $answer[75]f
      $answer[79]t
      $answer[85]f
      $answer[102]f
      $answer[103]f
      $answer[106]f
      $answer[111]t
      $answer[118]t
      $answer[119]f
      $answer[120]f
      $answer[121]t
      $answer[127]t
      $answer[131]f
      $answer[132]f
      $answer[136]t
      $answer[162]f
      $answer[165]t
      $answer[176]t
      $answer[183]f
      $answer[186]t
      $answer[190]t
      $answer[192]f
      $answer[193]f
      $answer[195]t
      $answer[196]f
      $answer[198]f
      $answer[200]f
      $answer[204]t
      $answer[206]f
      $answer[208]t
      $answer[218]t
      $answer[230]f
      $answer[234]f
      $answer[235]t
      $answer[236]f
      $answer[238]f
      $answer[250]t
      $answer[253]f
      $answer[255]t
      $answer[256]f
      $answer[267]t
      $answer[270]t
      $answer[271]f
      return $this->c;
   }
   
  function scale_Pa(){
      $this-> c = 0;
      $answer[15]t
      $answer[16]t
      $answer[21]t
      $answer[22]t
      $answer[23]t
      $answer[41]t
      $answer[80]f
      $answer[94]f
      $answer[97]f
      $answer[98]t
      $answer[99]t
      $answer[103]t
      $answer[109]f
      $answer[112]t
      $answer[137]t
      $answer[143]t
      $answer[144]t
      $answer[145]t
      $answer[161]t
      $answer[233]t
      $answer[243]f
      $answer[254]f
      $answer[258]t
      $answer[265]f
      $answer[270]t
      $answer[276]t
      $answer[282]f
      $answer[283]f
      $answer[284]t
      $answer[285]f
      $answer[296]f
      $answer[304]t
      $answer[306]t
      $answer[313]f
      $answer[314]f
      $answer[332]t
      $answer[333]t
      $answer[335]t
      $answer[354]t
      $answer[360]t
      return $this->c;
   }
   
   function scale_Pt(){
      $this-> c = 0;
      $answer[2]f
      $answer[8]f
      $answer[10]t
      $answer[15]t
      $answer[22]t
      $answer[30]t
      $answer[32]f
      $answer[37]t
      $answer[55]t
      $answer[64]t
      $answer[72]t
      $answer[81]t
      $answer[88]t
      $answer[93]t
      $answer[108]f
      $answer[129]t
      $answer[139]f
      $answer[146]t
      $answer[164]f
      $answer[169]t   
      $answer[173]f
      $answer[174]t
      $answer[195]t
      $answer[217]t
      $answer[241]t
      $answer[272]t
      $answer[274]t
      $answer[276]t
      $answer[284]t
      $answer[288]t
      $answer[292]f
      $answer[300]t
      $answer[301]t
      $answer[303]t
      $answer[307]t
      $answer[308]t
      $answer[309]t
      $answer[312]t
      $answer[315]t
      $answer[316]t
      $answer[319]t
      $answer[320]f
      $answer[324]t
      $answer[325]t
      $answer[236]t
      $answer[327]t
      $answer[328]t
      $answer[330]t
      return $this->c;
   }
   
   function scale_Es(){
      $this-> c = 0;
      $answer[5]f
      $answer[8]f
      $answer[11]f
      $answer[15]t
      $answer[16]t
      $answer[20]t
      $answer[21]t
      $answer[22]t
      $answer[30]t
      $answer[31]t
      $answer[33]f
      $answer[34]t
      $answer[37]t
      $answer[41]t
      $answer[43]t
      $answer[45]t
      $answer[47]t
      $answer[64]t
      $answer[84]t
      $answer[89]f
      $answer[90]f
      $answer[91]t
      $answer[105]f
      $answer[137]t
      $answer[144]t
      $answer[146]t
      $answer[164]f
      $answer[165]t
      $answer[167]t
      $answer[169]t
      $answer[176]f
      $answer[178]f
      $answer[179]t
      $answer[181]t
      $answer[189]t
      $answer[191]f
      $answer[209]f
      $answer[217]t
      $answer[220]t
      $answer[228]t
      $answer[232]t
      $answer[233]t
      $answer[241]t
      $answer[246]t
      $answer[251]t
      $answer[254]f
      $answer[255]t
      $answer[267]t
      $answer[272]t
      $answer[273]t
      $answer[275]f
      $answer[276]t
      $answer[277]f
      $answer[278]t
      $answer[279]f
      $answer[280]t
      $answer[286]t
      $answer[289]f
      $answer[290]t
      $answer[291]t
      $answer[294]f
      $answer[295]t
      $answer[297]t
      $answer[298]t
      $answer[302]t
      $answer[306]t
      $answer[310]t
      $answer[315]t
      $answer[318]t
      $answer[319]t
      $answer[321]t
      $answer[322]t
      $answer[324]t
      $answer[328]t
      $answer[331]t
      $answer[332]t
      $answer[342]f
      $answer[354]t
      return $this->c;
   }
   
   function scale_Ma(){
      $this-> c = 0;
      $answer[12]t
      $answer[14]t
      $answer[20]t
      $answer[22]t
      $answer[49]t
      $answer[54]t
      $answer[60]t
      $answer[84]t
      $answer[86]t
      $answer[87]f
      $answer[92]f
      $answer[97]t
      $answer[99]f
      $answer[105]f
      $answer[106]f
      $answer[112]t
      $answer[121]t
      $answer[130]t
      $answer[135]f
      $answer[144]t
      $answer[153]f
      $answer[154]t
      $answer[158]f
      $answer[166]f
      $answer[167]t
      $answer[168]t
      $answer[181]t
      $answer[189]t
      $answer[199]t
      $answer[204]t
      $answer[205]t
      $answer[210]t
      $answer[211]t
      $answer[217]t
      $answer[219]t
      $answer[226]t
      $answer[228]t
      $answer[237]t
      $answer[241]t
      $answer[242]f
      $answer[243]t
      $answer[247]t
      $answer[249]t
      $answer[252]t
      $answer[262]f
      $answer[268]t
      return $this->c;
   }
   
   function scale_Ls(){
      $this-> c = 0;
      $answer[24]f
      $answer[30]t
      $answer[31]f
      $answer[48]f
      $answer[55]t
      $answer[69]t
      $answer[78]f
      $answer[85]f
      $answer[99]t
      $answer[103]t
      $answer[105]f
      $answer[109]t
      $answer[111]f
      $answer[126]t
      $answer[130]f
      $answer[134]t
      $answer[157]t
      $answer[160]t
      $answer[166]t
      $answer[180]f
      $answer[184]t
      $answer[188]f
      $answer[206]f
      $answer[208]f
      $answer[214]t
      $answer[230]f
      $answer[236]f
      $answer[242]t
      $answer[250]t
      $answer[254]f
      $answer[261]f
      $answer[264]t
      $answer[266]f
      $answer[274]t
      $answer[279]f
      $answer[283]t
      $answer[288]t
      $answer[296]t
      $answer[301]t
      $answer[307]t
      $answer[320]f
      $answer[325]t
      $answer[327]f
      $answer[334]f
      $answer[336]t
      $answer[337]t
      $answer[339]f
      $answer[341]f
      $answer[343]f
      $answer[344]f
      $answer[346]t
      $answer[347]t
      $answer[349]f
      $answer[350]t
      $answer[351]t
      $answer[352]f
      $answer[353]f
      $answer[356]t
      $answer[357]f
      $answer[358]f
      $answer[359]f
      $answer[361]f
      $answer[362]f
      $answer[363]t
      $answer[365]f
      $answer[366]t
      $answer[367]t
      $answer[368]t
      $answer[369]f
      return $this->c;
   }
}

?>