<?php
//Sumales 1 por naco estupido
//Perfil de escalas suplementarias MMPI-2

class supplementaryScalesMale{

   private $c;

   //sumatoria de respuesta verdadero
   function calif_True($answer){
      if($answer == 'true'){
         $this->c++;
      }
   }
   
   //Sumatoria de respuesta falso
   function calif_False($answer){
     if($answer == 'false'){
         $this->c++;
     }
   }

   function scale_A($answer = array()){
      $this->calif_True($answer[31]);
      $this->calif_True($answer[38]);
      $this->calif_True($answer[56]);
      $this->calif_True($answer[65]);
      $this->calif_True($answer[82]);
      $this->calif_True($answer[127]);
      $this->calif_True($answer[135]);
      $this->calif_True($answer[215]);
      $this->calif_True($answer[233]);
      $this->calif_True($answer[243]);
      $this->calif_True($answer[251]);
      $this->calif_True($answer[273]);
      $this->calif_True($answer[277]);
      $this->calif_True($answer[289]);
      $this->calif_True($answer[301]);
      $this->calif_True($answer[309]);
      $this->calif_True($answer[310]);
      $this->calif_True($answer[311]);
      $this->calif_True($answer[325]);
      $this->calif_True($answer[338]);
      $this->calif_True($answer[339]);
      $this->calif_True($answer[341]);
      $this->calif_True($answer[347]);
      $this->calif_False($answer[388]);
      $this->calif_True($answer[390]);
      $this->calif_True($answer[391]);
      $this->calif_True($answer[392]);
      $this->calif_True($answer[400]);
      $this->calif_True($answer[408]);
      $this->calif_True($answer[411]);
      $this->calif_True($answer[415]);
      $this->calif_True($answer[421]);
      $this->calif_True($answer[428]);
      $this->calif_True($answer[442]);
      $this->calif_True($answer[448]);
      $this->calif_True($answer[451]);
      $this->calif_True($answer[464]);
      $this->calif_True($answer[469]);
      return $this->c;
   }

   function scale_R($answer = array()){
      $this->calif_False($answer[1]);
      $this->calif_False($answer[7]);
      $this->calif_False($answer[10]);
      $this->calif_False($answer[14]);
      $this->calif_False($answer[37]);
      $this->calif_False($answer[45]);
      $this->calif_False($answer[69]);
      $this->calif_False($answer[112]);
      $this->calif_False($answer[118]);
      $this->calif_False($answer[120]);
      $this->calif_False($answer[129]);
      $this->calif_False($answer[134]);
      $this->calif_False($answer[142]);
      $this->calif_False($answer[168]);
      $this->calif_False($answer[178]);
      $this->calif_False($answer[189]);
      $this->calif_False($answer[197]);
      $this->calif_False($answer[199]);
      $this->calif_False($answer[248]);
      $this->calif_False($answer[255]);
      $this->calif_False($answer[256]);
      $this->calif_False($answer[297]);
      $this->calif_False($answer[330]);
      $this->calif_False($answer[346]);
      $this->calif_False($answer[350]);
      $this->calif_False($answer[353]);
      $this->calif_False($answer[359]);
      $this->calif_False($answer[363]);
      $this->calif_False($answer[365]);
      $this->calif_False($answer[422]);
      $this->calif_False($answer[423]);
      $this->calif_False($answer[430]);
      $this->calif_False($answer[432]);
      $this->calif_False($answer[449]);
      $this->calif_False($answer[456]);
      $this->calif_False($answer[465]);
      return $this->c;
 }

   function scale_Fyo($answer = array()){
      $this->calif_True($answer[2]);
      $this->calif_False($answer[21]);
      $this->calif_False($answer[31]);
      $this->calif_False($answer[32]);
      $this->calif_True($answer[33]);
      $this->calif_False($answer[36]);
      $this->calif_False($answer[39]);
      $this->calif_True($answer[45]);
      $this->calif_False($answer[53]);
      $this->calif_False($answer[60]);
      $this->calif_False($answer[70]);
      $this->calif_False($answer[82]);
      $this->calif_False($answer[87]);
      $this->calif_True($answer[98]);
      $this->calif_False($answer[119]);
      $this->calif_False($answer[128]);
      $this->calif_True($answer[141]);
      $this->calif_True($answer[159]);
      $this->calif_True($answer[169]);
      $this->calif_False($answer[175]);
      $this->calif_True($answer[177]);
      $this->calif_True($answer[179]);
      $this->calif_True($answer[189]);
      $this->calif_False($answer[196]);
      $this->calif_True($answer[199]);
      $this->calif_True($answer[209]);
      $this->calif_True($answer[213]);
      $this->calif_False($answer[221]);
      $this->calif_False($answer[225]);
      $this->calif_False($answer[229]);
      $this->calif_True($answer[230]);
      $this->calif_False($answer[236]);
      $this->calif_True($answer[245]);
      $this->calif_False($answer[246]);
      $this->calif_False($answer[307]);
      $this->calif_False($answer[310]);
      $this->calif_False($answer[316]);
      $this->calif_True($answer[323]);
      $this->calif_False($answer[328]);
      $this->calif_True($answer[385]);
      $this->calif_False($answer[391]);
      $this->calif_False($answer[394]);
      $this->calif_True($answer[406]);
      $this->calif_True($answer[413]);
      $this->calif_True($answer[425]);
      $this->calif_false($answer[441]);
      $this->calif_false($answer[447]);
      $this->calif_false($answer[458]);
      $this->calif_false($answer[464]);
      $this->calif_false($answer[469]);
      $this->calif_false($answer[471]);
      return $this->c;
 }

 function scale_A_MAC($answer = array()){
    $this->calif_True($answer[7]);
    $this->calif_True($answer[24]);
    $this->calif_True($answer[36]);
    $this->calif_True($answer[49]);
    $this->calif_True($answer[52]);
    $this->calif_True($answer[69]);
    $this->calif_True($answer[72]);
    $this->calif_False($answer[73]);
    $this->calif_True($answer[82]);
    $this->calif_True($answer[84]);
    $this->calif_True($answer[103]);
    $this->calif_True($answer[105]);
    $this->calif_False($answer[107]);
    $this->calif_True($answer[113]);
    $this->calif_True($answer[115]);
    $this->calif_False($answer[117]);
    $this->calif_True($answer[128]);
    $this->calif_False($answer[137]);
    $this->calif_False($answer[160]);
    $this->calif_False($answer[166]);
    $this->calif_True($answer[172]);
    $this->calif_True($answer[202]);
    $this->calif_True($answer[214]);
    $this->calif_True($answer[224]);
    $this->calif_True($answer[229]);
    $this->calif_True($answer[238]);
    $this->calif_False($answer[251]);
    $this->calif_True($answer[257]);
    $this->calif_True($answer[266]);
    $this->calif_True($answer[180]);
    $this->calif_False($answer[287]);
    $this->calif_False($answer[299]);
    $this->calif_False($answer[325]);
    $this->calif_True($answer[342]);
    $this->calif_True($answer[344]);
    $this->calif_True($answer[387]);
    $this->calif_True($answer[408]);
    $this->calif_True($answer[412]);
    $this->calif_True($answer[414]);
    $this->calif_True($answer[422]);
    $this->calif_True($answer[434]);
    $this->calif_True($answer[439]);
    $this->calif_True($answer[445]);
    $this->calif_True($answer[472]);
    $this->calif_True($answer[502]);
    $this->calif_True($answer[506]);
    $this->calif_True($answer[549]);
    return $this->c;
 }

 function scale_HR($answer = array()){
    $this->calif_False($answer[1]);
    $this->calif_False($answer[15]);
    $this->calif_False($answer[29]);
    $this->calif_True($answer[67]);
    $this->calif_False($answer[69]);
    $this->calif_False($answer[77]);
    $this->calif_True($answer[79]);
    $this->calif_False($answer[89]);
    $this->calif_False($answer[98]);
    $this->calif_False($answer[116]);
    $this->calif_False($answer[129]);
    $this->calif_False($answer[153]);
    $this->calif_False($answer[169]);
    $this->calif_False($answer[171]);
    $this->calif_True($answer[207]);
    $this->calif_True($answer[286]);
    $this->calif_False($answer[293]);
    $this->calif_True($answer[305]);
    $this->calif_False($answer[344]);
    $this->calif_False($answer[390]);
    $this->calif_True($answer[398]);
    $this->calif_False($answer[400]);
    $this->calif_False($answer[420]);
    $this->calif_False($answer[433]);
    $this->calif_False($answer[440]);
    $this->calif_False($answer[460]);
    $this->calif_True($answer[471]);   
    return $this->c;
 }

 function scale_Do($answer = array()){
    $this->calif_False($answer[31]);
    $this->calif_False($answer[52]);
    $this->calif_True($answer[55]);
    $this->calif_False($answer[70]);
    $this->calif_False($answer[73]);
    $this->calif_False($answer[82]);
    $this->calif_False($answer[172]);
    $this->calif_False($answer[201]);
    $this->calif_False($answer[202]);
    $this->calif_True($answer[207]);
    $this->calif_False($answer[227]);
    $this->calif_True($answer[232]);
    $this->calif_False($answer[243]);
    $this->calif_True($answer[244]);
    $this->calif_False($answer[275]);
    $this->calif_False($answer[309]);
    $this->calif_True($answer[384]);
    $this->calif_False($answer[399]);
    $this->calif_False($answer[412]);
    $this->calif_True($answer[416]);
    $this->calif_False($answer[470]);
    $this->calif_False($answer[473]);
    return $this->c;
 }

 function scale_Rs($answer = array()){
    $this->calif_False($answer[7]);
    $this->calif_False($answer[27]);
    $this->calif_False($answer[29]);
    $this->calif_False($answer[32]);
    $this->calif_False($answer[84]);
    $this->calif_True($answer[100]);
    $this->calif_False($answer[103]);
    $this->calif_False($answer[105]);
    $this->calif_False($answer[145]);
    $this->calif_True($answer[160]);
    $this->calif_False($answer[164]);
    $this->calif_False($answer[169]);
    $this->calif_True($answer[199]);
    $this->calif_False($answer[201]);
    $this->calif_False($answer[235]);
    $this->calif_True($answer[266]);
    $this->calif_False($answer[275]);
    $this->calif_False($answer[358]);
    $this->calif_False($answer[412]);
    $this->calif_False($answer[418]);
    $this->calif_False($answer[430]);
    $this->calif_False($answer[431]);
    $this->calif_False($answer[432]);
    $this->calif_True($answer[440]);
    $this->calif_False($answer[456]);
    $this->calif_True($answer[467]);
    $this->calif_False($answer[468]);
    $this->calif_False($answer[470]);
    return $this->c;
 }

 function scale_Dpr($answer = array()){
    $this->calif_False($answer[2]);
    $this->calif_False($answer[3]);
    $this->calif_False($answer[9]);
    $this->calif_False($answer[10]);
    $this->calif_True($answer[15]);
    $this->calif_True($answer[16]);
    $this->calif_False($answer[20]);
    $this->calif_True($answer[28]);
    $this->calif_True($answer[31]);
    $this->calif_True($answer[38]);
    $this->calif_False($answer[43]);
    $this->calif_True($answer[71]);
    $this->calif_True($answer[73]);
    $this->calif_True($answer[81]);
    $this->calif_True($answer[82]);
    $this->calif_False($answer[95]);
    $this->calif_True($answer[110]);
    $this->calif_True($answer[130]);
    $this->calif_False($answer[131]);
    $this->calif_False($answer[140]);
    $this->calif_False($answer[148]);
    $this->calif_False($answer[152]);
    $this->calif_True($answer[215]);
    $this->calif_True($answer[218]);
    $this->calif_False($answer[223]);
    $this->calif_True($answer[233]);
    $this->calif_True($answer[269]);
    $this->calif_True($answer[273]);
    $this->calif_True($answer[299]);
    $this->calif_True($answer[302]);
    $this->calif_True($answer[325]);
    $this->calif_True($answer[331]);
    $this->calif_True($answer[339]);
    $this->calif_True($answer[357]);
    $this->calif_False($answer[405]);
    $this->calif_True($answer[408]);
    $this->calif_True($answer[411]);
    $this->calif_True($answer[449]);
    $this->calif_True($answer[464]);
    $this->calif_True($answer[469]);
    $this->calif_True($answer[472]);
    return $this->c;
 }

 function scale_GM($answer = array()){
    $this->calif_False($answer[4]);
    $this->calif_True($answer[8]);
    $this->calif_True($answer[20]);
    $this->calif_False($answer[23]);
    $this->calif_False($answer[44]);
    $this->calif_False($answer[64]);
    $this->calif_False($answer[70]);
    $this->calif_False($answer[73]);
    $this->calif_False($answer[74]);
    $this->calif_False($answer[80]);
    $this->calif_False($answer[100]);
    $this->calif_False($answer[137]);
    $this->calif_True($answer[143]);
    $this->calif_False($answer[146]);
    $this->calif_True($answer[152]);
    $this->calif_True($answer[159]);
    $this->calif_True($answer[163]);
    $this->calif_True($answer[176]);
    $this->calif_False($answer[187]);
    $this->calif_True($answer[199]);
    $this->calif_True($answer[214]);
    $this->calif_True($answer[237]);
    $this->calif_False($answer[289]);
    $this->calif_True($answer[321]);
    $this->calif_False($answer[331]);
    $this->calif_True($answer[350]);
    $this->calif_False($answer[364]);
    $this->calif_True($answer[385]);
    $this->calif_True($answer[388]);
    $this->calif_False($answer[392]);
    $this->calif_False($answer[395]);
    $this->calif_True($answer[401]);
    $this->calif_False($answer[435]);
    $this->calif_False($answer[438]);
    $this->calif_True($answer[440]);
    $this->calif_False($answer[441]);
    $this->calif_True($answer[462]);
    $this->calif_True($answer[467]);
    $this->calif_False($answer[469]);
    $this->calif_False($answer[471]);
    $this->calif_True($answer[474]);
    $this->calif_False($answer[497]);
    $this->calif_False($answer[509]);
    $this->calif_False($answer[519]);
    $this->calif_False($answer[532]);
    $this->calif_False($answer[536]);
    return $this->c;
 }

 function scale_GF($answer = array()){
    $this->calif_False($answer[1]);
    $this->calif_False($answer[27]);
    $this->calif_True($answer[62]);
    $this->calif_False($answer[63]);
    $this->calif_True($answer[67]);
    $this->calif_False($answer[68]);
    $this->calif_False($answer[79]);
    $this->calif_False($answer[84]);
    $this->calif_False($answer[105]);
    $this->calif_True($answer[119]);
    $this->calif_True($answer[121]);
    $this->calif_False($answer[123]);
    $this->calif_True($answer[128]);
    $this->calif_False($answer[133]);
    $this->calif_False($answer[155]);
    $this->calif_False($answer[197]);
    $this->calif_False($answer[201]);
    $this->calif_True($answer[203]);
    $this->calif_False($answer[220]);
    $this->calif_False($answer[231]);
    $this->calif_False($answer[238]);
    $this->calif_False($answer[239]);
    $this->calif_False($answer[250]);
    $this->calif_False($answer[257]);
    $this->calif_True($answer[263]);
    $this->calif_False($answer[264]);
    $this->calif_True($answer[266]);
    $this->calif_False($answer[272]);
    $this->calif_False($answer[287]);
    $this->calif_True($answer[353]);
    $this->calif_True($answer[384]);
    $this->calif_False($answer[406]);
    $this->calif_False($answer[417]);
    $this->calif_True($answer[426]);
    $this->calif_True($answer[449]);
    $this->calif_True($answer[456]);
    $this->calif_False($answer[465]);
    $this->calif_True($answer[473]);
    $this->calif_False($answer[477]);
    $this->calif_False($answer[487]);
    $this->calif_False($answer[510]);
    $this->calif_False($answer[511]);
    $this->calif_False($answer[537]);
    $this->calif_False($answer[548]);
    $this->calif_False($answer[550]);
    $this->calif_True($answer[552]);
    return $this->c;
 }

 function scale_EPK($answer = array()){
   $this->calif_False($answer[2]);
   $this->calif_False($answer[3]);
   $this->calif_False($answer[9]);
   $this->calif_True($answer[16]);
   $this->calif_True($answer[17]);
   $this->calif_True($answer[22]);
   $this->calif_True($answer[23]);
   $this->calif_True($answer[30]);
   $this->calif_True($answer[31]);
   $this->calif_True($answer[32]);
   $this->calif_True($answer[37]);
   $this->calif_True($answer[39]);
   $this->calif_True($answer[48]);
   $this->calif_False($answer[49]);
   $this->calif_True($answer[52]);
   $this->calif_True($answer[56]);
   $this->calif_True($answer[59]);
   $this->calif_True($answer[65]);
   $this->calif_False($answer[75]);
   $this->calif_True($answer[82]);
   $this->calif_True($answer[85]);
   $this->calif_True($answer[92]);
   $this->calif_True($answer[94]);
   $this->calif_False($answer[95]);
   $this->calif_True($answer[101]);
   $this->calif_False($answer[125]);
   $this->calif_True($answer[135]);
   $this->calif_False($answer[140]);
   $this->calif_True($answer[150]);
   $this->calif_True($answer[168]);
   $this->calif_True($answer[170]);
   $this->calif_True($answer[196]);
   $this->calif_True($answer[221]);
   $this->calif_True($answer[274]);
   $this->calif_True($answer[277]);
   $this->calif_True($answer[302]);
   $this->calif_True($answer[303]);
   $this->calif_True($answer[305]);
   $this->calif_True($answer[316]);
   $this->calif_True($answer[319]);
   $this->calif_True($answer[327]);
   $this->calif_True($answer[328]);
   $this->calif_True($answer[339]);
   $this->calif_True($answer[347]);
   $this->calif_True($answer[349]);
   $this->calif_True($answer[367]);
}

function scale_EPS($answer = array()){
   $this->calif_False($answer[3]);
   $this->calif_False($answer[9]);
   $this->calif_True($answer[17]);
   $this->calif_True($answer[20]);
   $this->calif_True($answer[21]);
   $this->calif_True($answer[31]);
   $this->calif_True($answer[32]);
   $this->calif_True($answer[37]);
   $this->calif_True($answer[38]);
   $this->calif_True($answer[44]);
   $this->calif_False($answer[45]);
   $this->calif_True($answer[48]);
   $this->calif_True($answer[56]);
   $this->calif_True($answer[59]);
   $this->calif_True($answer[65]);
   $this->calif_False($answer[75]);
   $this->calif_True($answer[85]);
   $this->calif_True($answer[94]);
   $this->calif_False($answer[95]);
   $this->calif_True($answer[116]);
   $this->calif_True($answer[135]);
   $this->calif_False($answer[141]);
   $this->calif_True($answer[145]);
   $this->calif_True($answer[150]);
   $this->calif_False($answer[165]);
   $this->calif_True($answer[168]);
   $this->calif_True($answer[170]);
   $this->calif_True($answer[180]);
   $this->calif_False($answer[208]);
   $this->calif_True($answer[218]);
   $this->calif_True($answer[221]);
   $this->calif_False($answer[223]);
   $this->calif_True($answer[273]);
   $this->calif_True($answer[274]);
   $this->calif_True($answer[277]);
   $this->calif_False($answer[280]);
   $this->calif_True($answer[299]);
   $this->calif_True($answer[301]);
   $this->calif_True($answer[304]);
   $this->calif_True($answer[305]);
   $this->calif_True($answer[311]);
   $this->calif_True($answer[316]);
   $this->calif_True($answer[319]);
   $this->calif_True($answer[325]);
   $this->calif_True($answer[328]);
   $this->calif_False($answer[372]);
   $this->calif_True($answer[377]);
   $this->calif_True($answer[386]);
   $this->calif_True($answer[400]);
   $this->calif_False($answer[405]);
   $this->calif_True($answer[463]);
   $this->calif_True($answer[464]);
   $this->calif_True($answer[469]);
   $this->calif_True($answer[471]);
   $this->calif_True($answer[475]);
   $this->calif_True($answer[479]);
   $this->calif_True($answer[515]);
   $this->calif_True($answer[516]);
   $this->calif_False($answer[564]);
   $this->calif_True($answer[565]);
}
 
function scale_ls1($answer = array()){
   $this->calif_False($answer[49]);
   $this->calif_True($answer[158]);
   $this->calif_True($answer[161]);
   $this->calif_True($answer[167]);
   $this->calif_True($answer[185]);
   $this->calif_True($answer[243]);
   $this->calif_False($answer[262]);
   $this->calif_True($answer[265]);
   $this->calif_True($answer[275]);
   $this->calif_False($answer[280]);
   $this->calif_True($answer[289]);
   $this->calif_False($answer[321]);
   $this->calif_False($answer[342]);
   $this->calif_False($answer[360]);

}

function scale_ls2($answer = array()){
   $this->calif_False($answer[86]);
   $this->calif_True($answer[337]);
   $this->calif_False($answer[340]);
   $this->calif_False($answer[353]);
   $this->calif_False($answer[359]);
   $this->calif_False($answer[363]);
   $this->calif_True($answer[367]);
   $this->calif_True($answer[370]);
}

function scale_ls3($answer = array()){
   $this->calif_True($answer[31]);
   $this->calif_True($answer[56]);
   $this->calif_True($answer[104]);
   $this->calif_True($answer[110]);
   $this->calif_True($answer[135]);
   $this->calif_True($answer[284]);
   $this->calif_True($answer[302]);
   $this->calif_True($answer[308]);
   $this->calif_True($answer[326]);
   $this->calif_True($answer[328]);
   $this->calif_True($answer[338]);
   $this->calif_True($answer[347]);
   $this->calif_True($answer[348]);
   $this->calif_True($answer[358]);
   $this->calif_True($answer[365]);
   $this->calif_True($answer[368]);
   $this->calif_True($answer[369]);
}

function scale_Fp($answer = array()){
   $this->calif_True($answer[281]);
   $this->calif_True($answer[299]);
   $this->calif_True($answer[303]);
   $this->calif_True($answer[311]);
   $this->calif_True($answer[317]);
   $this->calif_True($answer[319]);
   $this->calif_True($answer[322]);
   $this->calif_True($answer[323]);
   $this->calif_True($answer[329]);
   $this->calif_True($answer[332]);
   $this->calif_True($answer[333]);
   $this->calif_True($answer[334]);
   $this->calif_False($answer[383]);
   $this->calif_True($answer[387]);
   $this->calif_True($answer[395]);
   $this->calif_False($answer[404]);
   $this->calif_True($answer[407]);
   $this->calif_True($answer[431]);
   $this->calif_True($answer[450]);
   $this->calif_True($answer[454]);
   $this->calif_True($answer[463]);
   $this->calif_True($answer[468]);
   $this->calif_True($answer[476]);
   $this->calif_True($answer[478]);
   $this->calif_True($answer[484]);
   $this->calif_True($answer[489]);
   $this->calif_False($answer[501]);
   $this->calif_True($answer[506]);
   $this->calif_True($answer[516]);
   $this->calif_True($answer[517]);
   $this->calif_True($answer[520]);
   $this->calif_True($answer[524]);
   $this->calif_True($answer[525]);
   $this->calif_True($answer[526]);
   $this->calif_True($answer[528]);
   $this->calif_True($answer[530]);
   $this->calif_True($answer[539]);
   $this->calif_True($answer[540]);
   $this->calif_True($answer[544]);
   $this->calif_True($answer[555]);
}

}
?>