<?php
//Perfil de escalas suplementarias MMPI-2

class supplementaryScalesMale{

   private $c;

   //sumatoria de respuesta verdadero
   function calif_True($answer){
      if($answer == 'true'){
         $this->c++;
      }
   }
   
   //Sumatoria de respuesta falso
   function calif_False($answer){
     if($answer == 'false'){
         $this->c++;
     }
   }

   function scale_A($answer = array()){
      $this->calif_True($answer[30]);
      $this->calif_True($answer[37]);
      $this->calif_True($answer[55]);
      $this->calif_True($answer[64]);
      $this->calif_True($answer[81]);
      $this->calif_True($answer[126]);
      $this->calif_True($answer[134]);
      $this->calif_True($answer[214]);
      $this->calif_True($answer[232]);
      $this->calif_True($answer[242]);
      $this->calif_True($answer[250]);
      $this->calif_True($answer[272]);
      $this->calif_True($answer[276]);
      $this->calif_True($answer[288]);
      $this->calif_True($answer[300]);
      $this->calif_True($answer[308]);
      $this->calif_True($answer[309]);
      $this->calif_True($answer[310]);
      $this->calif_True($answer[324]);
      $this->calif_True($answer[327]);
      $this->calif_True($answer[337]);
      $this->calif_True($answer[338]);
      $this->calif_True($answer[340]);
      $this->calif_True($answer[346]);
      $this->calif_False($answer[387]);
      $this->calif_True($answer[389]);
      $this->calif_True($answer[390]);
      $this->calif_True($answer[393]);
      $this->calif_True($answer[399]);
      $this->calif_True($answer[407]);
      $this->calif_True($answer[410]);
      $this->calif_True($answer[414]);
      $this->calif_True($answer[420]);
      $this->calif_True($answer[427]);
      $this->calif_True($answer[441]);
      $this->calif_True($answer[447]);
      $this->calif_True($answer[450]);
      $this->calif_True($answer[463]);
      $this->calif_True($answer[468]);
      return $this->c;
   }

   function scale_R($answer = array()){
      $this->calif_False($answer[0]);
      $this->calif_False($answer[6]);
      $this->calif_False($answer[9]);
      $this->calif_False($answer[13]);
      $this->calif_False($answer[36]);
      $this->calif_False($answer[44]);
      $this->calif_False($answer[68]);
      $this->calif_False($answer[111]);
      $this->calif_False($answer[117]);
      $this->calif_False($answer[119]);
      $this->calif_False($answer[127]);
      $this->calif_False($answer[133]);
      $this->calif_False($answer[141]);
      $this->calif_False($answer[167]);
      $this->calif_False($answer[177]);
      $this->calif_False($answer[188]);
      $this->calif_False($answer[196]);
      $this->calif_False($answer[198]);
      $this->calif_False($answer[247]);
      $this->calif_False($answer[254]);
      $this->calif_False($answer[255]);
      $this->calif_False($answer[296]);
      $this->calif_False($answer[329]);
      $this->calif_False($answer[345]);
      $this->calif_False($answer[349]);
      $this->calif_False($answer[352]);
      $this->calif_False($answer[353]);
      $this->calif_False($answer[358]);
      $this->calif_False($answer[362]);
      $this->calif_False($answer[364]);
      $this->calif_False($answer[421]);
      $this->calif_False($answer[422]);
      $this->calif_False($answer[429]);
      $this->calif_False($answer[431]);
      $this->calif_False($answer[448]);
      $this->calif_False($answer[455]);
      $this->calif_False($answer[464]);
      return $this->c;
 }

   function scale_Fyo($answer = array()){
      $this->calif_True($answer[1]);
      $this->calif_False($answer[22]);
      $this->calif_False($answer[30]);
      $this->calif_False($answer[31]);
      $this->calif_True($answer[32]);
      $this->calif_False($answer[35]);
      $this->calif_False($answer[38]);
      $this->calif_True($answer[44]);
      $this->calif_False($answer[52]);
      $this->calif_False($answer[59]);
      $this->calif_False($answer[69]);
      $this->calif_False($answer[81]);
      $this->calif_False($answer[86]);
      $this->calif_True($answer[97]);
      $this->calif_False($answer[118]);
      $this->calif_False($answer[127]);
      $this->calif_True($answer[140]);
      $this->calif_True($answer[158]);
      $this->calif_True($answer[168]);
      $this->calif_False($answer[174]);
      $this->calif_True($answer[176]);
      $this->calif_True($answer[178]);
      $this->calif_True($answer[188]);
      $this->calif_False($answer[195]);
      $this->calif_True($answer[198]);
      $this->calif_True($answer[208]);
      $this->calif_True($answer[212]);
      $this->calif_False($answer[214]);
      $this->calif_False($answer[220]);
      $this->calif_False($answer[224]);
      $this->calif_False($answer[228]);
      $this->calif_True($answer[229]);
      $this->calif_False($answer[235]);
      $this->calif_True($answer[244]);
      $this->calif_False($answer[245]);
      $this->calif_False($answer[306]);
      $this->calif_False($answer[309]);
      $this->calif_False($answer[315]);
      $this->calif_True($answer[322]);
      $this->calif_False($answer[327]);
      $this->calif_True($answer[384]);
      $this->calif_False($answer[390]);
      $this->calif_False($answer[393]);
      $this->calif_True($answer[405]);
      $this->calif_True($answer[412]);
      $this->calif_True($answer[424]);
      $this->calif_false($answer[440]);
      $this->calif_false($answer[446]);
      $this->calif_false($answer[457]);
      $this->calif_false($answer[463]);
      $this->calif_false($answer[468]);
      $this->calif_false($answer[470]);
      return $this->c;
 }

 function scale_A_MAC($answer = array()){
    $this->calif_True($answer[6]);
    $this->calif_True($answer[23]);
    $this->calif_True($answer[35]);
    $this->calif_True($answer[48]);
    $this->calif_True($answer[51]);
    $this->calif_True($answer[68]);
    $this->calif_True($answer[71]);
    $this->calif_False($answer[72]);
    $this->calif_True($answer[81]);
    $this->calif_True($answer[83]);
    $this->calif_True($answer[102]);
    $this->calif_True($answer[104]);
    $this->calif_False($answer[106]);
    $this->calif_True($answer[112]);
    $this->calif_True($answer[114]);
    $this->calif_False($answer[116]);
    $this->calif_True($answer[127]);
    $this->calif_False($answer[136]);
    $this->calif_False($answer[159]);
    $this->calif_False($answer[165]);
    $this->calif_False($answer[167]);
    $this->calif_True($answer[171]);
    $this->calif_True($answer[201]);
    $this->calif_True($answer[213]);
    $this->calif_True($answer[223]);
    $this->calif_True($answer[228]);
    $this->calif_True($answer[237]);
    $this->calif_False($answer[250]);
    $this->calif_True($answer[256]);
    $this->calif_True($answer[265]);
    $this->calif_True($answer[179]);
    $this->calif_False($answer[286]);
    $this->calif_False($answer[298]);
    $this->calif_False($answer[324]);
    $this->calif_True($answer[341]);
    $this->calif_True($answer[343]);
    $this->calif_True($answer[386]);
    $this->calif_True($answer[407]);
    $this->calif_True($answer[411]);
    $this->calif_True($answer[413]);
    $this->calif_True($answer[421]);
    $this->calif_True($answer[433]);
    $this->calif_True($answer[438]);
    $this->calif_True($answer[444]);
    $this->calif_True($answer[455]);
    $this->calif_True($answer[472]);
    $this->calif_True($answer[501]);
    $this->calif_True($answer[505]);
    $this->calif_True($answer[548]);
    return $this->c;
 }

 //En esta me quedé
 function scale_HR($answer = array()){
    $this->calif_False($answer[1]);
    $this->calif_False($answer[15]);
    $this->calif_False($answer[29]);
    $this->calif_True($answer[67]);
    $this->calif_False($answer[69]);
    $this->calif_False($answer[77]);
    $this->calif_True($answer[79]);
    $this->calif_False($answer[89]);
    $this->calif_False($answer[98]);
    $this->calif_False($answer[116]);
    $this->calif_False($answer[129]);
    $this->calif_False($answer[153]);
    $this->calif_False($answer[169]);
    $this->calif_False($answer[171]);
    $this->calif_True($answer[207]);
    $this->calif_True($answer[286]);
    $this->calif_False($answer[293]);
    $this->calif_True($answer[305]);
    $this->calif_False($answer[344]);
    $this->calif_False($answer[390]);
    $this->calif_True($answer[398]);
    $this->calif_False($answer[400]);
    $this->calif_False($answer[420]);
    $this->calif_False($answer[433]);
    $this->calif_False($answer[440]);
    $this->calif_False($answer[460]);
    $this->calif_True($answer[471]);   
    return $this->c;
 }

 function scale_Do($answer = array()){
    $this->calif_False($answer[31]);
    $this->calif_False($answer[52]);
    $this->calif_True($answer[55]);
    $this->calif_False($answer[70]);
    $this->calif_False($answer[73]);
    $this->calif_False($answer[82]);
    $this->calif_False($answer[172]);
    $this->calif_False($answer[201]);
    $this->calif_False($answer[202]);
    $this->calif_True($answer[207]);
    $this->calif_False($answer[227]);
    $this->calif_True($answer[232]);
    $this->calif_False($answer[243]);
    $this->calif_True($answer[244]);
    $this->calif_False($answer[275]);
    $this->calif_False($answer[309]);
    $this->calif_True($answer[384]);
    $this->calif_False($answer[399]);
    $this->calif_False($answer[412]);
    $this->calif_True($answer[416]);
    $this->calif_False($answer[470]);
    $this->calif_False($answer[473]);
    return $this->c;
 }

 function scale_Rs($answer = array()){
    $this->calif_False($answer[7]);
    $this->calif_False($answer[27]);
    $this->calif_False($answer[29]);
    $this->calif_False($answer[32]);
    $this->calif_False($answer[84]);
    $this->calif_True($answer[100]);
    $this->calif_False($answer[103]);
    $this->calif_False($answer[105]);
    $this->calif_False($answer[145]);
    $this->calif_True($answer[160]);
    $this->calif_False($answer[164]);
    $this->calif_False($answer[169]);
    $this->calif_True($answer[199]);
    $this->calif_False($answer[201]);
    $this->calif_False($answer[235]);
    $this->calif_True($answer[266]);
    $this->calif_False($answer[275]);
    $this->calif_False($answer[358]);
    $this->calif_False($answer[412]);
    $this->calif_False($answer[418]);
    $this->calif_False($answer[430]);
    $this->calif_False($answer[431]);
    $this->calif_False($answer[432]);
    $this->calif_True($answer[440]);
    $this->calif_False($answer[456]);
    $this->calif_True($answer[467]);
    $this->calif_False($answer[468]);
    $this->calif_False($answer[470]);
    return $this->c;
 }

 function scale_Dpr($answer = array()){
    $this->calif_False($answer[2]);
    $this->calif_False($answer[3]);
    $this->calif_False($answer[9]);
    $this->calif_False($answer[10]);
    $this->calif_True($answer[15]);
    $this->calif_True($answer[16]);
    $this->calif_False($answer[20]);
    $this->calif_True($answer[28]);
    $this->calif_True($answer[31]);
    $this->calif_True($answer[38]);
    $this->calif_False($answer[43]);
    $this->calif_True($answer[71]);
    $this->calif_True($answer[73]);
    $this->calif_True($answer[81]);
    $this->calif_True($answer[82]);
    $this->calif_False($answer[95]);
    $this->calif_True($answer[110]);
    $this->calif_True($answer[130]);
    $this->calif_False($answer[131]);
    $this->calif_False($answer[140]);
    $this->calif_False($answer[148]);
    $this->calif_False($answer[152]);
    $this->calif_True($answer[215]);
    $this->calif_True($answer[218]);
    $this->calif_False($answer[223]);
    $this->calif_True($answer[233]);
    $this->calif_True($answer[269]);
    $this->calif_True($answer[273]);
    $this->calif_True($answer[299]);
    $this->calif_True($answer[302]);
    $this->calif_True($answer[325]);
    $this->calif_True($answer[331]);
    $this->calif_True($answer[339]);
    $this->calif_True($answer[357]);
    $this->calif_False($answer[405]);
    $this->calif_True($answer[408]);
    $this->calif_True($answer[411]);
    $this->calif_True($answer[449]);
    $this->calif_True($answer[464]);
    $this->calif_True($answer[469]);
    $this->calif_True($answer[472]);
    return $this->c;
 }

 function scale_GM($answer = array()){
    $this->calif_False($answer[4]);
    $this->calif_True($answer[8]);
    $this->calif_True($answer[20]);
    $this->calif_False($answer[23]);
    $this->calif_False($answer[44]);
    $this->calif_False($answer[64]);
    $this->calif_False($answer[70]);
    $this->calif_False($answer[73]);
    $this->calif_False($answer[74]);
    $this->calif_False($answer[80]);
    $this->calif_False($answer[100]);
    $this->calif_False($answer[137]);
    $this->calif_True($answer[143]);
    $this->calif_False($answer[146]);
    $this->calif_True($answer[152]);
    $this->calif_True($answer[159]);
    $this->calif_True($answer[163]);
    $this->calif_True($answer[176]);
    $this->calif_False($answer[187]);
    $this->calif_True($answer[199]);
    $this->calif_True($answer[214]);
    $this->calif_True($answer[237]);
    $this->calif_False($answer[289]);
    $this->calif_True($answer[321]);
    $this->calif_False($answer[331]);
    $this->calif_True($answer[350]);
    $this->calif_False($answer[364]);
    $this->calif_True($answer[385]);
    $this->calif_True($answer[388]);
    $this->calif_False($answer[392]);
    $this->calif_False($answer[395]);
    $this->calif_True($answer[401]);
    $this->calif_False($answer[435]);
    $this->calif_False($answer[438]);
    $this->calif_True($answer[440]);
    $this->calif_False($answer[441]);
    $this->calif_True($answer[462]);
    $this->calif_True($answer[467]);
    $this->calif_False($answer[469]);
    $this->calif_False($answer[471]);
    $this->calif_True($answer[474]);
    $this->calif_False($answer[497]);
    $this->calif_False($answer[509]);
    $this->calif_False($answer[519]);
    $this->calif_False($answer[532]);
    $this->calif_False($answer[536]);
    return $this->c;
 }

 function scale_GF($answer = array()){
    $this->calif_False($answer[1]);
    $this->calif_False($answer[27]);
    $this->calif_True($answer[62]);
    $this->calif_False($answer[63]);
    $this->calif_True($answer[67]);
    $this->calif_False($answer[68]);
    $this->calif_False($answer[79]);
    $this->calif_False($answer[84]);
    $this->calif_False($answer[105]);
    $this->calif_True($answer[119]);
    $this->calif_True($answer[121]);
    $this->calif_False($answer[123]);
    $this->calif_True($answer[128]);
    $this->calif_False($answer[133]);
    $this->calif_False($answer[155]);
    $this->calif_False($answer[197]);
    $this->calif_False($answer[201]);
    $this->calif_True($answer[203]);
    $this->calif_False($answer[220]);
    $this->calif_False($answer[231]);
    $this->calif_False($answer[238]);
    $this->calif_False($answer[239]);
    $this->calif_False($answer[250]);
    $this->calif_False($answer[257]);
    $this->calif_True($answer[263]);
    $this->calif_False($answer[264]);
    $this->calif_True($answer[266]);
    $this->calif_False($answer[272]);
    $this->calif_False($answer[287]);
    $this->calif_True($answer[353]);
    $this->calif_True($answer[384]);
    $this->calif_False($answer[406]);
    $this->calif_False($answer[417]);
    $this->calif_True($answer[426]);
    $this->calif_True($answer[449]);
    $this->calif_True($answer[456]);
    $this->calif_False($answer[465]);
    $this->calif_True($answer[473]);
    $this->calif_False($answer[477]);
    $this->calif_False($answer[487]);
    $this->calif_False($answer[510]);
    $this->calif_False($answer[511]);
    $this->calif_False($answer[537]);
    $this->calif_False($answer[548]);
    $this->calif_False($answer[550]);
    $this->calif_True($answer[552]);
    return $this->c;
 }

 function scale_EPK($answer = array()){
   $this->calif_False($answer[2]);
   $this->calif_False($answer[3]);
   $this->calif_False($answer[9]);
   $this->calif_True($answer[16]);
   $this->calif_True($answer[17]);
   $this->calif_True($answer[22]);
   $this->calif_True($answer[23]);
   $this->calif_True($answer[30]);
   $this->calif_True($answer[31]);
   $this->calif_True($answer[32]);
   $this->calif_True($answer[37]);
   $this->calif_True($answer[39]);
   $this->calif_True($answer[48]);
   $this->calif_False($answer[49]);
   $this->calif_True($answer[52]);
   $this->calif_True($answer[56]);
   $this->calif_True($answer[59]);
   $this->calif_True($answer[65]);
   $this->calif_False($answer[75]);
   $this->calif_True($answer[82]);
   $this->calif_True($answer[85]);
   $this->calif_True($answer[92]);
   $this->calif_True($answer[94]);
   $this->calif_False($answer[95]);
   $this->calif_True($answer[101]);
   $this->calif_False($answer[125]);
   $this->calif_True($answer[135]);
   $this->calif_False($answer[140]);
   $this->calif_True($answer[150]);
   $this->calif_True($answer[168]);
   $this->calif_True($answer[170]);
   $this->calif_True($answer[196]);
   $this->calif_True($answer[221]);
   $this->calif_True($answer[274]);
   $this->calif_True($answer[277]);
   $this->calif_True($answer[302]);
   $this->calif_True($answer[303]);
   $this->calif_True($answer[305]);
   $this->calif_True($answer[316]);
   $this->calif_True($answer[319]);
   $this->calif_True($answer[327]);
   $this->calif_True($answer[328]);
   $this->calif_True($answer[339]);
   $this->calif_True($answer[347]);
   $this->calif_True($answer[349]);
   $this->calif_True($answer[367]);
}

function scale_EPS($answer = array()){
   $this->calif_False($answer[3]);
   $this->calif_False($answer[9]);
   $this->calif_True($answer[17]);
   $this->calif_True($answer[20]);
   $this->calif_True($answer[21]);
   $this->calif_True($answer[31]);
   $this->calif_True($answer[32]);
   $this->calif_True($answer[37]);
   $this->calif_True($answer[38]);
   $this->calif_True($answer[44]);
   $this->calif_False($answer[45]);
   $this->calif_True($answer[48]);
   $this->calif_True($answer[56]);
   $this->calif_True($answer[59]);
   $this->calif_True($answer[65]);
   $this->calif_False($answer[75]);
   $this->calif_True($answer[85]);
   $this->calif_True($answer[94]);
   $this->calif_False($answer[95]);
   $this->calif_True($answer[116]);
   $this->calif_True($answer[135]);
   $this->calif_False($answer[141]);
   $this->calif_True($answer[145]);
   $this->calif_True($answer[150]);
   $this->calif_False($answer[165]);
   $this->calif_True($answer[168]);
   $this->calif_True($answer[170]);
   $this->calif_True($answer[180]);
   $this->calif_False($answer[208]);
   $this->calif_True($answer[218]);
   $this->calif_True($answer[221]);
   $this->calif_False($answer[223]);
   $this->calif_True($answer[273]);
   $this->calif_True($answer[274]);
   $this->calif_True($answer[277]);
   $this->calif_False($answer[280]);
   $this->calif_True($answer[299]);
   $this->calif_True($answer[301]);
   $this->calif_True($answer[304]);
   $this->calif_True($answer[305]);
   $this->calif_True($answer[311]);
   $this->calif_True($answer[316]);
   $this->calif_True($answer[319]);
   $this->calif_True($answer[325]);
   $this->calif_True($answer[328]);
   $this->calif_False($answer[372]);
   $this->calif_True($answer[377]);
   $this->calif_True($answer[386]);
   $this->calif_True($answer[400]);
   $this->calif_False($answer[405]);
   $this->calif_True($answer[463]);
   $this->calif_True($answer[464]);
   $this->calif_True($answer[469]);
   $this->calif_True($answer[471]);
   $this->calif_True($answer[475]);
   $this->calif_True($answer[479]);
   $this->calif_True($answer[515]);
   $this->calif_True($answer[516]);
   $this->calif_False($answer[564]);
   $this->calif_True($answer[565]);
}
 
function scale_ls1($answer = array()){
   $this->calif_False($answer[49]);
   $this->calif_True($answer[158]);
   $this->calif_True($answer[161]);
   $this->calif_True($answer[167]);
   $this->calif_True($answer[185]);
   $this->calif_True($answer[243]);
   $this->calif_False($answer[262]);
   $this->calif_True($answer[265]);
   $this->calif_True($answer[275]);
   $this->calif_False($answer[280]);
   $this->calif_True($answer[289]);
   $this->calif_False($answer[321]);
   $this->calif_False($answer[342]);
   $this->calif_False($answer[360]);

}

function scale_ls2($answer = array()){
   $this->calif_False($answer[86]);
   $this->calif_True($answer[337]);
   $this->calif_False($answer[340]);
   $this->calif_False($answer[353]);
   $this->calif_False($answer[359]);
   $this->calif_False($answer[363]);
   $this->calif_True($answer[367]);
   $this->calif_True($answer[370]);
}

function scale_ls3($answer = array()){
   $this->calif_True($answer[31]);
   $this->calif_True($answer[56]);
   $this->calif_True($answer[104]);
   $this->calif_True($answer[110]);
   $this->calif_True($answer[135]);
   $this->calif_True($answer[284]);
   $this->calif_True($answer[302]);
   $this->calif_True($answer[308]);
   $this->calif_True($answer[326]);
   $this->calif_True($answer[328]);
   $this->calif_True($answer[338]);
   $this->calif_True($answer[347]);
   $this->calif_True($answer[348]);
   $this->calif_True($answer[358]);
   $this->calif_True($answer[365]);
   $this->calif_True($answer[368]);
   $this->calif_True($answer[369]);
}

function scale_Fp($answer = array()){
   $this->calif_True($answer[281]);
   $this->calif_True($answer[299]);
   $this->calif_True($answer[303]);
   $this->calif_True($answer[311]);
   $this->calif_True($answer[317]);
   $this->calif_True($answer[319]);
   $this->calif_True($answer[322]);
   $this->calif_True($answer[323]);
   $this->calif_True($answer[329]);
   $this->calif_True($answer[332]);
   $this->calif_True($answer[333]);
   $this->calif_True($answer[334]);
   $this->calif_False($answer[383]);
   $this->calif_True($answer[387]);
   $this->calif_True($answer[395]);
   $this->calif_False($answer[404]);
   $this->calif_True($answer[407]);
   $this->calif_True($answer[431]);
   $this->calif_True($answer[450]);
   $this->calif_True($answer[454]);
   $this->calif_True($answer[463]);
   $this->calif_True($answer[468]);
   $this->calif_True($answer[476]);
   $this->calif_True($answer[478]);
   $this->calif_True($answer[484]);
   $this->calif_True($answer[489]);
   $this->calif_False($answer[501]);
   $this->calif_True($answer[506]);
   $this->calif_True($answer[516]);
   $this->calif_True($answer[517]);
   $this->calif_True($answer[520]);
   $this->calif_True($answer[524]);
   $this->calif_True($answer[525]);
   $this->calif_True($answer[526]);
   $this->calif_True($answer[528]);
   $this->calif_True($answer[530]);
   $this->calif_True($answer[539]);
   $this->calif_True($answer[540]);
   $this->calif_True($answer[544]);
   $this->calif_True($answer[555]);
}

}
?>